os: linux
dist: bionic
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgtkmm-3.0-dev

compiler:
  - clang
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
# Download dependencies and build project
  - conan install .
# Call your build system
  - cmake . -G "Unix Makefiles"
  - cmake --build .
# Run your tests
  - ctest .