os: linux
dist: bionic
language: c++

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgtkmm-3.0-dev

compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user

  - pip install ninja # as used @home, to avoid complications
script:
# Download dependencies and build project
  - conan install .
# Call your build system
  - cmake . -G "Ninja"
  - cmake --build .
# Run your tests
  - ctest .